version: "3"
services:

  front:
    build: front/
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - back

  back:
    build: back/
    expose:
      - "8080"
    volumes:
      - ./back/src/test/resources/videogen:/tmp/videogen_dir
